manifest:
  self:
    path: config
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: slaetreteals
      url-base: https://github.com/SlaetZMK
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
      
    - name: zmk-keyboards
      remote: slaetzmk
      revision: main
      
    - name: zmk-leader-key
      remote: urob
      revision: v0.3 # set to same as ZMK version above
  self:
    path: config
